version: '3.4'

services:
  folder2:
    image: folder2
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
